name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/README.pdf README.md --pdf-engine=xelatex
      
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/README-zh-cn.pdf README-zh-cn.md --pdf-engine=xelatex
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
